"""Untrusted SVG parsing (ARCHITECTURE_REVIEW.md §10a). Every uploaded file is untrusted
input, always, regardless of extension or claimed type. This module implements every
*content-level* control §10a requires:

- content-sniffed type check (magic bytes / structure, never filename/extension)
- file-size cap, checked before any parsing
- XXE defense: `defusedxml` with DTDs, external entities, and external resource
  resolution all explicitly forbidden
- a hard element-count cap enforced *during* the walk (not after), bounding both memory
  and wall-clock time for a pathological-but-small-byte-count file (e.g. deeply
  repeated elements) without needing a separate timeout mechanism
- a hard nesting-depth cap (`MAX_NESTING_DEPTH`), enforced by an iterative (not
  recursive) tree walk — see `_walk`'s own docstring for the incident this closes
  (PHASE2_NESTED_SVG_CORRECTION_REPORT.md)
- `<script>`/event-handler-attribute/external-reference stripping — nothing that could
  execute or fetch anything survives into the SIR
- the Sanitized Intermediate Representation (`SanitizeResult.shapes`) is the *only*
  thing that crosses back out — no raw markup, no `Element` objects, no file handle

This module's own processing takes a `bytes` object and never itself writes to a
quarantine directory or any other path on disk. Correction (RT-2,
PHASE2_INDEPENDENT_RED_TEAM_REPORT.md / PHASE2_CORRECTION_REPORT.md): a prior version of
this docstring additionally claimed the *entire* upload path was in-memory-only, which
independent testing (and this correction's own re-verification, both via live
`/proc/<pid>/fd` monitoring during real uploads) found to be false above 1MB — Starlette's
`UploadFile` spools to a real, immediately-unlinked OS temp file
(`tempfile.SpooledTemporaryFile(max_size=1MB)`) *before* this module or the endpoint ever
sees the bytes, for any upload over 1MB, which is the common case given this project's own
5MB (SVG) / 20MB (raster) caps. What does still hold, and is the property that actually
matters for path traversal specifically: that temp file's path is generated by Python's
`tempfile` module from process-random state, never from the uploaded filename — so no
attacker-controlled filename can ever influence where anything is written, regardless of
whether a given upload happens to spool.

Scope limitation, disclosed rather than silently assumed (PHASE2_GAP_ANALYSIS.md §3.4):
this does not run inside a separate OS-level subprocess/container with its own
credential-free identity, unlike §10a's "narrowly-scoped worker/subprocess" language —
that is a genuine infrastructure control this implementation does not provide."""

import re
from dataclasses import dataclass, field
from xml.etree.ElementTree import Element  # noqa: S405 — type only; parsing uses defusedxml exclusively

from defusedxml import DefusedXmlException
from defusedxml.ElementTree import ParseError, fromstring

MAX_SVG_FILE_SIZE_BYTES = 5 * 1024 * 1024  # 5 MB
MAX_RASTER_FILE_SIZE_BYTES = 20 * 1024 * 1024  # 20 MB — calibration-only, no parsing
MAX_ELEMENTS = 5_000
MAX_NESTING_DEPTH = 200  # PHASE2_NESTED_SVG_CORRECTION_REPORT.md — see _walk's docstring
MAX_COORDINATE = 1_000_000  # matches app.application.spatial_validation's bound

DANGEROUS_TAGS = {"script", "foreignobject", "animate", "animatetransform", "set", "iframe", "use", "image"}
XLINK_HREF = "{http://www.w3.org/1999/xlink}href"


@dataclass
class SirShape:
    """One normalized shape — the only unit of data the rest of the import pipeline
    (candidate detection, classification) is allowed to consume."""

    shape_type: str  # rect | circle | text
    x: float
    y: float
    width: float | None = None
    height: float | None = None
    radius: float | None = None
    text: str | None = None


@dataclass
class SanitizeResult:
    shapes: list[SirShape] = field(default_factory=list)
    objects_discovered: int = 0
    unsupported_object_count: int = 0
    warnings: list[str] = field(default_factory=list)


class SvgRejected(Exception):
    def __init__(self, reason: str):
        self.reason = reason
        super().__init__(reason)


def _looks_like_svg(content: bytes) -> bool:
    """Content-sniffed, not filename/extension-based (§10a: 'content-sniffed (magic
    bytes, not filename/extension) file-type check; reject on mismatch')."""
    head = content[:1024].lstrip(b"\xef\xbb\xbf \t\r\n")
    if head.startswith(b"<?xml") or head.startswith(b"<svg"):
        return True
    return b"<svg" in content[:4096]


def _looks_like_png(content: bytes) -> bool:
    return content[:8] == b"\x89PNG\r\n\x1a\n"


def _looks_like_jpeg(content: bytes) -> bool:
    return content[:3] == b"\xff\xd8\xff"


def validate_raster_image(content: bytes, *, declared_format: str) -> None:
    """Calibration-only import (§10: "ImageImporter... explicitly performs
    calibration-only import — no shape auto-detection — stated as NOT IMPLEMENTED for
    that capability rather than faked"). No parsing beyond a magic-byte/size check —
    there is no shape extraction to sanitize output from."""
    if len(content) > MAX_RASTER_FILE_SIZE_BYTES:
        raise SvgRejected(f"file exceeds the {MAX_RASTER_FILE_SIZE_BYTES} byte size limit")
    if declared_format == "png" and not _looks_like_png(content):
        raise SvgRejected("file content does not match the PNG magic bytes")
    if declared_format == "jpeg" and not _looks_like_jpeg(content):
        raise SvgRejected("file content does not match the JPEG magic bytes")
    if declared_format not in ("png", "jpeg"):
        raise SvgRejected(f"unsupported raster format: {declared_format}")


def sanitize_svg(content: bytes) -> SanitizeResult:
    if len(content) > MAX_SVG_FILE_SIZE_BYTES:
        raise SvgRejected(f"file exceeds the {MAX_SVG_FILE_SIZE_BYTES} byte size limit")
    if not _looks_like_svg(content):
        raise SvgRejected("file content does not appear to be SVG (magic-byte check failed)")

    try:
        root = fromstring(content, forbid_dtd=True, forbid_entities=True, forbid_external=True)
    except DefusedXmlException as exc:
        raise SvgRejected(f"rejected by XML security controls: {exc}") from exc
    except ParseError as exc:
        raise SvgRejected(f"malformed XML: {exc}") from exc
    except Exception as exc:  # noqa: BLE001 — any other parser failure is a rejection, never a 500
        raise SvgRejected(f"unparseable file: {exc}") from exc

    result = SanitizeResult()
    _walk(root, result)
    return result


def _local_tag(tag: str) -> str:
    return tag.split("}")[-1].lower() if "}" in tag else tag.lower()


def _safe_float(value: str | None, default: float = 0.0) -> float:
    """Strips a trailing unit suffix (px/mm/%) defensively — SVG numeric attributes are
    technically unitless per spec, but malformed/hostile input is common. Out-of-range
    values (the "enormous coordinate values" attack) collapse to the default rather than
    propagating a value that could overflow downstream arithmetic."""
    if value is None:
        return default
    try:
        f = float(re.sub(r"[a-zA-Z%]+$", "", value.strip()))
    except ValueError:
        return default
    if f != f or f in (float("inf"), float("-inf")):  # NaN/Infinity
        return default
    if not (-MAX_COORDINATE <= f <= MAX_COORDINATE):
        return default
    return f


def _walk(root: Element, result: SanitizeResult) -> None:
    """Iterative (explicit-stack) pre-order walk — deliberately not a recursive
    function calling itself per child, which a prior version of this module was.

    PHASE2_NESTED_SVG_CORRECTION_REPORT.md: a deeply nested SVG (~960+ levels of
    `<g>`, independently reproduced by red-team testing at a small, trivially
    craftable file size) drove that recursive version past Python's own interpreter
    call-stack limit, raising an uncaught `RecursionError` — a resource-exhaustion
    defect distinct from (and not covered by) `MAX_ELEMENTS`, which bounds *breadth*
    (how many sibling elements this walk is willing to look at) but did nothing to
    bound *depth* (how many levels of nested containers this walk is willing to
    descend into). An explicit stack removes Python's own call-stack depth as an
    attack surface entirely, regardless of how deep a document claims to be — pushing
    another `(element, depth)` tuple onto a Python list never risks a `RecursionError`.

    `MAX_NESTING_DEPTH` (200) is a separate, deterministic business rule on top of
    that, not a recursion-limit workaround: a legitimate data-center floor plan —
    even a heavily layered CAD/Visio export grouping racks, equipment, and
    annotations into their own named layers — has no plausible reason to nest more
    than a handful of `<g>` levels deep. 200 is generous against any realistic floor
    plan while remaining far below where any recursive implementation (this one or a
    future regression back to one) would ever approach Python's own default
    recursion limit (1000), and while remaining a small, cheap, O(depth) list even at
    depths in the tens of thousands — an attacker cannot force unbounded CPU or
    memory purely through nesting, since traversal is rejected outright the moment
    the limit is exceeded, before any of that depth is actually walked.

    Traversal order (and therefore `result.shapes` ordering, `objects_discovered`
    counts, and warnings) is identical to the previous recursive implementation:
    each element is fully processed — and its own children are then fully exhausted,
    depth-first — before its next sibling is visited, exactly as
    `for child in list(element): process(child); _walk(child, result)` used to
    produce. Children are pushed in reverse so the leftmost is popped (and thus
    visited) next."""
    stack: list[tuple[Element, int]] = [(child, 1) for child in reversed(list(root))]
    while stack:
        element, depth = stack.pop()

        if result.objects_discovered >= MAX_ELEMENTS:
            result.warnings.append(f"element count cap ({MAX_ELEMENTS}) reached; remaining elements ignored")
            return
        result.objects_discovered += 1
        tag = _local_tag(element.tag)

        if tag in DANGEROUS_TAGS:
            result.warnings.append(f"stripped disallowed element <{tag}>")
            result.unsupported_object_count += 1
            continue  # never descend into a stripped element's children either

        for attr in list(element.attrib):
            if attr.lower().startswith("on"):
                result.warnings.append(f"stripped event-handler attribute '{attr}' from <{tag}>")
                del element.attrib[attr]

        href = element.attrib.get("href") or element.attrib.get(XLINK_HREF)
        if href and re.match(r"^(https?:)?//|^[a-z][a-z0-9+.-]*:", href, re.IGNORECASE) and not href.startswith("#"):
            result.warnings.append(f"stripped external reference on <{tag}>: {href[:80]!r}")
            element.attrib.pop("href", None)
            element.attrib.pop(XLINK_HREF, None)

        if tag == "rect":
            result.shapes.append(
                SirShape(
                    shape_type="rect",
                    x=_safe_float(element.attrib.get("x")),
                    y=_safe_float(element.attrib.get("y")),
                    width=_safe_float(element.attrib.get("width")),
                    height=_safe_float(element.attrib.get("height")),
                )
            )
        elif tag == "circle":
            result.shapes.append(
                SirShape(
                    shape_type="circle",
                    x=_safe_float(element.attrib.get("cx")),
                    y=_safe_float(element.attrib.get("cy")),
                    radius=_safe_float(element.attrib.get("r")),
                )
            )
        elif tag == "text":
            text_content = "".join(element.itertext()).strip()[:255]
            result.shapes.append(
                SirShape(
                    shape_type="text", x=_safe_float(element.attrib.get("x")), y=_safe_float(element.attrib.get("y")),
                    text=text_content,
                )
            )
        elif tag in ("g", "svg", "defs"):
            pass  # containers only — no shape of their own
        else:
            result.unsupported_object_count += 1

        children = list(element)
        if children and depth >= MAX_NESTING_DEPTH:
            # Only rejecting here (an element *with* children, at the limit) rather
            # than unconditionally at `depth >= MAX_NESTING_DEPTH` matters at the exact
            # boundary: a leaf element sitting at depth MAX_NESTING_DEPTH is fully
            # processed and legitimate — there is nothing deeper to reject — only an
            # element that would require descending past the limit is rejected.
            raise SvgRejected(f"SVG nesting exceeds the {MAX_NESTING_DEPTH}-level depth limit")

        stack.extend((child, depth + 1) for child in reversed(children))
