import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { PageHeader } from "@/components/ui/ProductUi";
import { getRoomSpatialView } from "@/features/floor-plans/api";
import { listRooms } from "@/features/racks/api";
import type { RoomRack } from "@/types";

export function Layout3DPage(){
 const rooms=useQuery({queryKey:["rooms"],queryFn:listRooms}); const [roomId,setRoomId]=useState(""); const activeRoom=roomId||rooms.data?.items[0]?.id||"";
 const view=useQuery({queryKey:["spatial",activeRoom,"3d"],queryFn:()=>getRoomSpatialView(activeRoom),enabled:!!activeRoom});
 const [selected,setSelected]=useState<RoomRack|null>(null); const [yaw,setYaw]=useState(-28); const [pitch,setPitch]=useState(58); const [zoom,setZoom]=useState(.75);
 return <div className="page"><PageHeader eyebrow="Infrastructure" title="3D layout" description="Interactive perspective projection of authoritative room and rack placements." actions={<div className="flex gap-2"><Link to={activeRoom?`/floor-plans/room/${activeRoom}`:"/floor-plans"} className="action-secondary">2D floor plan</Link><button className="action-secondary" onClick={()=>{setYaw(-28);setPitch(58);setZoom(.75)}}>Reset / fit</button></div>}/>
 <div className="mb-3 flex gap-2"><select className="field max-w-sm" value={activeRoom} onChange={e=>{setRoomId(e.target.value);setSelected(null)}}>{rooms.data?.items.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><label className="text-xs text-slate-500">Orbit <input type="range" min="-80" max="80" value={yaw} onChange={e=>setYaw(+e.target.value)}/></label><label className="text-xs text-slate-500">Tilt <input type="range" min="35" max="75" value={pitch} onChange={e=>setPitch(+e.target.value)}/></label><label className="text-xs text-slate-500">Zoom <input type="range" min="0.4" max="1.4" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></div>
 <div className="grid gap-4 xl:grid-cols-[1fr_300px]"><div className="surface relative h-[580px] overflow-hidden" onWheel={e=>setZoom(z=>Math.max(.4,Math.min(1.4,z-e.deltaY*.001)))}><div className="absolute inset-[12%] origin-center border border-indigo-400/30 bg-slate-900" style={{transform:`perspective(900px) rotateX(${pitch}deg) rotateZ(${yaw}deg) scale(${zoom})`,transformStyle:"preserve-3d"}}>{view.data?.racks.map((rack,i)=><button key={rack.id} onClick={()=>setSelected(rack)} className="absolute grid place-items-center border border-indigo-300 bg-indigo-600/80 text-[11px] font-semibold shadow-xl" style={{left:`${((rack.x_mm??(i%4)*200+100)/(view.data?.room_width_mm||1000))*100}%`,top:`${((rack.y_mm??Math.floor(i/4)*250+100)/(view.data?.room_height_mm||1000))*100}%`,width:50,height:85,transform:`translate(-50%,-50%) rotate(${rack.rotation_deg??0}deg) translateZ(45px)`,transformStyle:"preserve-3d"}}>{rack.name}</button>)}</div><span className="absolute bottom-3 left-3 text-xs text-slate-500">Rendering defaults are view-only where room dimensions or coordinates are unavailable.</span></div>
 <aside className="surface p-4"><h2 className="font-semibold">Rack context</h2>{selected?<><h3 className="mt-3 text-lg font-semibold">{selected.name}</h3><p className="text-xs text-slate-500">{selected.asset_tag}</p><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-slate-500">Room</dt><dd>{view.data?.room_name}</dd></div><div><dt className="text-slate-500">Position</dt><dd>{selected.x_mm??"Unavailable"}, {selected.y_mm??"Unavailable"} mm</dd></div><div><dt className="text-slate-500">Rotation</dt><dd>{selected.rotation_deg??"Unavailable"}°</dd></div><div><dt className="text-slate-500">Capacity / occupied / free</dt><dd>Unavailable in spatial response</dd></div></dl><Link to={`/racks/${selected.id}`} className="action-primary mt-5 inline-block">Open Rack Elevation</Link></>:<p className="mt-3 text-sm text-slate-500">Select a rack in the room.</p>}<div className="mt-6 border-t border-slate-800 pt-3"><h3 className="text-xs font-semibold uppercase text-slate-500">Layers</h3><p className="mt-2 text-sm">✓ Room<br/>✓ Racks<br/><span className="text-slate-600">Equipment · future layer<br/>Power · Network · Cooling · Environment</span></p></div></aside></div></div>
}
