import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { PageHeader, StatusBadge } from "@/components/ui/ProductUi";
import { getNetworkTopology, getNetworkTrace } from "./api";

export function NetworkPage(){
 const [selected,setSelected]=useState(""); const [query,setQuery]=useState(""); const [type,setType]=useState("");
 const topology=useQuery({queryKey:["network","topology"],queryFn:getNetworkTopology});
 const trace=useQuery({queryKey:["network","trace",selected],queryFn:()=>getNetworkTrace(selected),enabled:!!selected});
 const devices=useMemo(()=>topology.data?.devices.filter(d=>(!type||d.device_type===type)&&(`${d.name} ${d.asset_tag}`.toLowerCase().includes(query.toLowerCase())))??[],[topology.data,query,type]);
 const interfaces=topology.data?.interfaces??[]; const links=topology.data?.connections??[]; const selectedDevice=topology.data?.devices.find(d=>d.id===selected);
 const positions=new Map(devices.map((d,i)=>[d.id,{x:100+(i%4)*210,y:75+Math.floor(i/4)*145}]));
 return <div className="page"><PageHeader eyebrow="Operate" title="Network" description="Authoritative physical inventory topology and modeled-path traceability." />
 <div className="mb-3 grid gap-2 sm:grid-cols-[1fr_220px_auto]"><input className="field" placeholder="Search device or asset tag" value={query} onChange={e=>setQuery(e.target.value)}/><select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="">All device types</option>{[...new Set(topology.data?.devices.map(d=>d.device_type))].map(t=><option key={t}>{t}</option>)}</select><button className="action-secondary" onClick={()=>{setQuery("");setType("")}}>Fit / reset</button></div>
 <div className="grid gap-4 xl:grid-cols-[1fr_320px]"><section className="surface min-h-[520px] overflow-auto p-3"><svg viewBox="0 0 900 500" className="h-[500px] min-w-[720px] w-full" aria-label="Network topology">{links.map(link=>{const a=interfaces.find(i=>i.id===link.interface_a_id),b=interfaces.find(i=>i.id===link.interface_b_id),pa=a&&positions.get(a.device_id),pb=b&&positions.get(b.device_id);return pa&&pb?<line key={link.id} x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y} stroke="#475569" strokeWidth="3" onClick={()=>setSelected(a!.device_id)}><title>{a?.name} ↔ {b?.name}</title></line>:null})}{devices.map(d=>{const p=positions.get(d.id)!;const core=d.device_type==="core_switch",endpoint=d.device_type==="endpoint";return <g key={d.id} onClick={()=>setSelected(d.id)} className="cursor-pointer"><rect x={p.x-70} y={p.y-28} width="140" height="56" rx="9" fill={selected===d.id?"#4338ca":core?"#0f766e":endpoint?"#1e293b":"#1d4ed8"} stroke="#64748b"/><text x={p.x} y={p.y-3} textAnchor="middle" fill="white" fontSize="13">{d.name}</text><text x={p.x} y={p.y+15} textAnchor="middle" fill="#cbd5e1" fontSize="10">{d.device_type.replace(/_/g," ")}</text></g>})}</svg></section>
 <aside className="surface p-4"><h2 className="font-semibold">Context</h2>{!selectedDevice?<p className="mt-3 text-sm text-slate-500">Select a device or physical link.</p>:<><div className="mt-3 flex items-center justify-between"><strong>{selectedDevice.name}</strong><StatusBadge label={selectedDevice.lifecycle_status}/></div><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-slate-500">Type</dt><dd>{selectedDevice.device_type}</dd></div><div><dt className="text-slate-500">Provenance</dt><dd>{selectedDevice.source}</dd></div></dl><h3 className="mt-5 text-sm font-semibold">Interfaces</h3><ul className="mt-2 space-y-2">{interfaces.filter(i=>i.device_id===selected).map(i=><li key={i.id} className="rounded bg-slate-900 p-2 text-xs"><b>{i.name}</b> · {i.oper_status}<br/><span className="text-slate-500">VLAN {i.native_vlan??"Unknown"} · {i.speed_mbps?`${i.speed_mbps} Mbps`:"Speed unavailable"}</span></li>)}</ul><h3 className="mt-5 text-sm font-semibold">Modeled path</h3>{trace.isLoading?<p className="text-sm text-slate-500">Tracing…</p>:trace.data?<><StatusBadge label={trace.data.state}/><p className="mt-2 text-xs text-slate-500">{trace.data.statement}</p><ol className="mt-3 border-l border-indigo-500 pl-3">{trace.data.hops.map((h,i)=><li key={`${h.device_id}-${i}`} className="mb-3 text-sm"><b>{h.device}</b><br/><span className="text-xs text-slate-500">{h.interface??"Interface unknown"} · VLAN {h.vlan??"Unknown"} · {h.operational_state??"Unknown"}</span></li>)}</ol></>:null}</>}</aside></div></div>
}
