"""phase1 initial schema

Revision ID: e9fd19228f19
Revises: 
Create Date: 2026-09-16 16:46:20.737095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e9fd19228f19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("result IN ('success', 'failure')", name=op.f('ck_audit_log_result_allowed')),
    sa.CheckConstraint("source IN ('ui', 'api', 'system', 'import')", name=op.f('ck_audit_log_source_allowed')),
    sa.PrimaryKeyConstraint('audit_id', 'timestamp', name=op.f('pk_audit_log')),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_key'))
    )
    op.create_index('ix_idempotency_key_key_endpoint', 'idempotency_key', ['key', 'endpoint'], unique=True)
    op.create_table('location_type',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_type')),
    sa.UniqueConstraint('code', name=op.f('uq_location_type_code'))
    )
    op.create_table('managed_asset',
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('asset_tag', sa.String(length=64), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decommissioned_at', sa.DateTime(), nullable=True),
    sa.Column('replaces_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('rack', 'equipment', 'pdu', 'ups', 'generator', 'power_panel', 'sensor', 'cable')", name=op.f('ck_managed_asset_asset_type_allowed')),
    sa.CheckConstraint("lifecycle_status IN ('planned', 'installed', 'active', 'reserved', 'maintenance', 'decommissioned', 'removed')", name=op.f('ck_managed_asset_lifecycle_status_allowed')),
    sa.ForeignKeyConstraint(['replaces_asset_id'], ['managed_asset.id'], name=op.f('fk_managed_asset_replaces_asset_id_managed_asset'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managed_asset')),
    sa.UniqueConstraint('asset_tag', name=op.f('uq_managed_asset_asset_tag')),
    sa.UniqueConstraint('replaces_asset_id', name='uq_managed_asset_replaces_asset_id')
    )
    op.create_table('organization',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('name', name=op.f('uq_organization_name'))
    )
    op.create_table('outbox_event',
    sa.Column('event_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'dispatched', 'failed')", name=op.f('ck_outbox_event_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event')),
    sa.UniqueConstraint('event_id', name=op.f('uq_outbox_event_event_id'))
    )
    op.create_index(op.f('ix_outbox_event_aggregate_id'), 'outbox_event', ['aggregate_id'], unique=False)
    op.create_index('ix_outbox_event_status_next_attempt', 'outbox_event', ['status', 'next_attempt_at'], unique=False)
    op.create_table('permission',
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('country',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_country_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_index(op.f('ix_country_organization_id'), 'country', ['organization_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_refresh_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_token_jti'))
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('role_assignment',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_type IN ('global', 'site', 'building')", name=op.f('ck_role_assignment_scope_type_allowed')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_assignment_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_role_assignment_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignment')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_role_assignment')
    )
    op.create_index(op.f('ix_role_assignment_role_id'), 'role_assignment', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignment_user_id'), 'role_assignment', ['user_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission'))
    )
    op.create_table('city',
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_city_country_id_country'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_index(op.f('ix_city_country_id'), 'city', ['country_id'], unique=False)
    op.create_table('site',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_site_city_id_city'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('code', name=op.f('uq_site_code'))
    )
    op.create_index(op.f('ix_site_city_id'), 'site', ['city_id'], unique=False)
    op.create_table('building',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_building_site_id_site'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_building')),
    sa.UniqueConstraint('site_id', 'code', name='uq_building_site_code')
    )
    op.create_index(op.f('ix_building_site_id'), 'building', ['site_id'], unique=False)
    op.create_table('floor',
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name=op.f('fk_floor_building_id_building'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floor')),
    sa.UniqueConstraint('building_id', 'level_number', name='uq_floor_building_level')
    )
    op.create_index(op.f('ix_floor_building_id'), 'floor', ['building_id'], unique=False)
    op.create_table('room',
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raised_floor', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], name=op.f('fk_room_floor_id_floor'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('floor_id', 'code', name='uq_room_floor_code')
    )
    op.create_index(op.f('ix_room_floor_id'), 'room', ['floor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_floor_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_floor_building_id'), table_name='floor')
    op.drop_table('floor')
    op.drop_index(op.f('ix_building_site_id'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_site_city_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_city_country_id'), table_name='city')
    op.drop_table('city')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_role_assignment_user_id'), table_name='role_assignment')
    op.drop_index(op.f('ix_role_assignment_role_id'), table_name='role_assignment')
    op.drop_table('role_assignment')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_country_organization_id'), table_name='country')
    op.drop_table('country')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_index('ix_outbox_event_status_next_attempt', table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_aggregate_id'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_table('organization')
    op.drop_table('managed_asset')
    op.drop_table('location_type')
    op.drop_index('ix_idempotency_key_key_endpoint', table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_table('audit_log')
    op.drop_table('app_user')
    # ### end Alembic commands ###
